version: '3.8'

services:
  sftp:
    build:
      context: .
    image: ghcr.io/concepting-com-br/sftp:${BUILD_VERSION}
    container_name: sftp
    hostname: sftp
    ports: 
      - 2222:2222
    depends_on:
      - etcd
      
  etcd:
    image: ghcr.io/concepting-com-br/etcd:1.0.0
    container_name: etcd
    hostname: etcd
    ports: 
      - 2379:2379
    volumes:
      - ./etc/default.json:/home/user/etc/sftp.json
      - etcd-data:/home/user/data

volumes:
  sftp-data:
  sftp-log:
  etcd-data:
  